package agent

import (
	"context"
	"fmt"
	"log"
	"strings"

	"codenite/worker/internal/config"
	"codenite/worker/internal/util"
)

type Worker struct {
	cfg        config.Config
	taskSource TaskSource
	ai         AIProvider
	vcs        VCSProvider
	seen       map[string]struct{}
}

func NewWorker(cfg config.Config, taskSource TaskSource, ai AIProvider, vcs VCSProvider) *Worker {
	return &Worker{
		cfg:        cfg,
		taskSource: taskSource,
		ai:         ai,
		vcs:        vcs,
		seen:       make(map[string]struct{}),
	}
}

func (w *Worker) RunOnce(ctx context.Context) error {
	tasks, err := w.taskSource.Fetch(ctx)
	if err != nil {
		return fmt.Errorf("fetch tasks: %w", err)
	}

	if len(tasks) == 0 {
		log.Println("no tasks found")
		return nil
	}

	for _, task := range tasks {
		if _, ok := w.seen[task.ID]; ok {
			log.Printf("task %s skipped: already processed in this worker session", task.ID)
			continue
		}
		w.seen[task.ID] = struct{}{}

		if err := w.processTask(ctx, task); err != nil {
			log.Printf("task %s failed: %v", task.ID, err)
		}
	}

	return nil
}

func (w *Worker) processTask(ctx context.Context, task Task) error {
	repoCfg, ok := w.cfg.Repositories[task.ProjectID]
	if !ok {
		log.Printf("task %s ignored: project %s not mapped", task.ID, task.ProjectID)
		return nil
	}

	repo := RepoTarget{FullName: repoCfg.Repo, BaseBranch: repoCfg.BaseBranch}
	if repo.BaseBranch == "" {
		repo.BaseBranch = "main"
	}

	repoPath, err := w.vcs.PrepareRepo(ctx, repo)
	if err != nil {
		return fmt.Errorf("prepare repo: %w", err)
	}

	branch := util.BranchName(task.ID, task.Title)
	if err := w.vcs.CreateBranch(ctx, repoPath, branch, repo.BaseBranch); err != nil {
		return fmt.Errorf("create branch: %w", err)
	}

	if w.cfg.Worker.DryRun {
		log.Printf("dry-run task=%s repo=%s branch=%s", task.ID, repo.FullName, branch)
		return nil
	}

	codingLabels := addLabel(removeLabel(task.Labels, w.cfg.TaskSource.Todoist.Label), "Coding")
	if err := w.taskSource.UpdateLabels(ctx, task.ID, codingLabels); err != nil {
		log.Printf("task %s update labels (Coding) failed: %v", task.ID, err)
	}
	task.Labels = codingLabels

	aiResult, err := w.ai.Develop(ctx, repoPath, repo.FullName, task)
	w.commentAIResult(ctx, task.ID, aiResult, err)
	if err != nil {
		return fmt.Errorf("ai develop: %w", err)
	}

	msg := fmt.Sprintf("feat: implement todoist task %s", task.ID)
	changed, err := w.vcs.CommitAll(ctx, repoPath, msg)
	if err != nil {
		return fmt.Errorf("commit changes: %w", err)
	}
	if !changed {
		log.Printf("task %s produced no changes", task.ID)
		return nil
	}

	if err := w.vcs.Push(ctx, repoPath, branch); err != nil {
		return fmt.Errorf("push branch: %w", err)
	}

	prTitle := fmt.Sprintf("[AI] %s", strings.TrimSpace(task.Title))
	prBody := buildPRBody(task)
	prURL, err := w.vcs.OpenPullRequest(ctx, repo.FullName, repo.BaseBranch, branch, prTitle, prBody, w.cfg.VCS.GitHub.Draft)
	if err != nil {
		return fmt.Errorf("open pr: %w", err)
	}

	finalLabels := addLabel(removeLabel(task.Labels, "Coding"), "PR Opened")
	if err := w.taskSource.UpdateLabels(ctx, task.ID, finalLabels); err != nil {
		log.Printf("task %s update labels (PR Opened) failed: %v", task.ID, err)
	}

	if w.cfg.Worker.CommentOnTask {
		comment := fmt.Sprintf("PR created: %s", prURL)
		if err := w.taskSource.Comment(ctx, task.ID, comment); err != nil {
			log.Printf("task %s comment failed: %v", task.ID, err)
		}
	}

	if w.cfg.Worker.CloseTaskOnPR {
		if err := w.taskSource.Close(ctx, task.ID); err != nil {
			log.Printf("task %s close failed: %v", task.ID, err)
		}
	}

	log.Printf("task %s completed PR=%s", task.ID, prURL)
	return nil
}

func addLabel(labels []string, label string) []string {
	for _, existing := range labels {
		if strings.EqualFold(existing, label) {
			return append([]string(nil), labels...)
		}
	}
	out := append([]string(nil), labels...)
	out = append(out, label)
	return out
}

func removeLabel(labels []string, label string) []string {
	out := make([]string, 0, len(labels))
	for _, existing := range labels {
		if strings.EqualFold(existing, label) {
			continue
		}
		out = append(out, existing)
	}
	return out
}

func buildPRBody(task Task) string {
	body := fmt.Sprintf("Automated implementation for Todoist task %s.\n\n", task.ID)
	body += fmt.Sprintf("Original task: %s\n\n", task.Title)
	if strings.TrimSpace(task.Description) != "" {
		body += "Description:\n"
		body += task.Description + "\n\n"
	}
	body += "Generated by worker agent (Todoist + Codex)."
	return body
}

func (w *Worker) commentAIResult(ctx context.Context, taskID string, result AIResult, developErr error) {
	status := "success"
	if developErr != nil {
		status = "failed"
	}

	header := fmt.Sprintf("AI execution `%s` (exit_code=%d).", status, result.ExitCode)
	comments := []string{header}

	if strings.TrimSpace(result.Stdout) != "" {
		comments = append(comments, chunkOutputForComments("AI stdout", result.Stdout)...)
	}
	if strings.TrimSpace(result.Stderr) != "" {
		comments = append(comments, chunkOutputForComments("AI stderr", result.Stderr)...)
	}
	if len(comments) == 1 {
		comments = append(comments, "AI output was empty.")
	}

	for _, comment := range comments {
		if err := w.taskSource.Comment(ctx, taskID, comment); err != nil {
			log.Printf("task %s AI output comment failed: %v", taskID, err)
		}
	}
}

func chunkOutputForComments(title, output string) []string {
	const maxChunk = 1500
	text := strings.TrimSpace(output)
	if text == "" {
		return nil
	}

	chunks := splitBySize(text, maxChunk)
	out := make([]string, 0, len(chunks))
	for i, chunk := range chunks {
		out = append(out, fmt.Sprintf("%s (%d/%d):\n```\n%s\n```", title, i+1, len(chunks), chunk))
	}
	return out
}

func splitBySize(s string, size int) []string {
	if size <= 0 {
		return []string{s}
	}
	if len(s) <= size {
		return []string{s}
	}

	parts := make([]string, 0, (len(s)+size-1)/size)
	for len(s) > size {
		cut := strings.LastIndexByte(s[:size], '\n')
		if cut <= 0 {
			cut = size
		}
		parts = append(parts, strings.TrimSpace(s[:cut]))
		s = strings.TrimSpace(s[cut:])
	}
	if strings.TrimSpace(s) != "" {
		parts = append(parts, strings.TrimSpace(s))
	}
	return parts
}
